hooter.tsxを作成及び編集　feature/9
yassun-youtube/the-hack-2022-nov-team-6 pull request #14
Opened 2022-12-14 08:20 UTC by kitou88C39

**What**
https://gyazo.com/fe431d25b361052022cfdbdc28d0fe7e

**Todo**
hooter.tsxを作成及び編集

上記作業のご確認をお願いします。

2022-12-14 09:01 UTC, takunagai approved these changes
コピーライトの文字修正で LGTM です。

2022-12-14 09:01 UTC, takunagai commented on app/hooter.tsx
> +        <p className='mt-8 text-base leading-6 text-center text-gray-500'>© 2016-2022 chinyuri</p>
一応、とりあえず "© 2022 Team Six" でいきましょう

2022-12-14 10:26 UTC, spka2yb9 requested changes
ご対応ありがとうございます！
細々した点をコメントしていますので、ご確認お願いいたします。

2022-12-14 10:26 UTC, spka2yb9 commented on app/hooter.tsx
> +        <p className='mt-8 text-base leading-6 text-center text-gray-500'>© 2016-2022 chinyuri</p>
コピーライトなどブログで共通してそうな部分はblog.config.tsにまとめているので、そちらを使用してもらえると！
https://github.com/yassun-youtube/the-hack-2022-nov-team-6/blob/afa498cbccc5043a9f3525804424d9ff4ea333e5/app/sample/html-template/page.tsx#L287

2022-12-14 10:26 UTC, spka2yb9 commented on app/hooter.tsx
> +            <a href='#' className='text-xl leading-6 text-gray-600 hover:text-gray-900'>
aタグはLinkコンポーネントに置き換えれられそうです！
https://beta.nextjs.org/docs/routing/linking-and-navigating

2022-12-14 10:26 UTC, spka2yb9 commented on app/hooter.tsx
> +export default function hooter() {
コンポーネント名は頭が大文字の命名にする必要があるっぽいです！
https://reactjs.org/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized
今回の場合は、```Footer```になるかと思います

2022-12-14 10:26 UTC, spka2yb9 commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
yarn installするとpackage-lock.jsonとは別にlockファイルができるみたいですね...。
saikiさんがvercelにデプロイして下さっている背景もあるので、今回はnpm installでライブラリをインストールして対応いただけると嬉しいです！
https://zenn.dev/mo_ri_regen/articles/package-lock-yarn-lock

2022-12-14 10:26 UTC, spka2yb9 commented on app/hooter.tsx
> +import Link from 'next/link'
※ 以下はファイル全体に対してのコメントです。

footerのような共通コンポーネントは/compoents/common/配下に配置していただけると！
https://www.notion.so/d30744791ca743bb93ccf9de2261f935

また、app直下のlayout.tsxに追加すると全ページに共通して表示されるので試してみていただけると！
```      
<body>
    {children}
    <Footer />
</body>
```

2022-12-14 10:46 UTC, yuhi-sa commented
[want]ファイル名、hooterではなくfooterでしょうか。

2022-12-14 10:48 UTC, yuhi-sa commented
[IMO]また、classNameで同じ内容を複数回利用していると思うので、変数化した方が可読性・保守性が上がるかなと思いました。

こちらと同様のコメントになります。動作には影響ないので無視していただいても大丈夫です！
https://github.com/yassun-youtube/the-hack-2022-nov-team-6/pull/13/files#r1048294859

2022-12-14 11:08 UTC, kitou88C39 commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
『npm install』でライブラリをインストールする場合、
『yarn remove』もした方が良いですか？

2022-12-15 10:45 UTC, spka2yb9 commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
今回はyarn.lockを削除してpackage-lock.jsonに統一するのが目的なので、不要かと思います！

2022-12-16 11:11 UTC, spka2yb9 approved these changes
LGTM!

2022-12-16 11:13 UTC, yuhi-sa approved these changes
LGTMです

2022-12-16 11:31 UTC, merged